### ISSUE TITLE
Cancelling unmarshalling

### ISSUE THREAD

**Issue by timblackwell** [gocarina/gocsv#24]
My use case is reading an extremely large CSV, coming from s3, processing these the rows and then outputting results in new CSV.

My problem is gracefully exiting early. I don't see anyway of stopping the CSV unmarshalling.
I was hoping that closing the input reader would work but it does not.

Any suggestions?

**Comment by pikanezi** [comment]
Are you using https://godoc.org/github.com/gocarina/gocsv#UnmarshalToChan ?

**Comment by timblackwell** [comment]
Yes I am using this method.
I have a few downstream consumers that need the input channel to be closed
before they can exit.

**Comment by pikanezi** [comment]
I don't see any clean way to do that. You could close the channel, but it would panic because you can't send values to a closed channel.

I don't know of any easy method to check if a channel is closed without trying to read from it.

If you have an idea to how we could do that without changing the API, i would be happy to hear it. If not, the only solution would be to write another function which take two channels, one which will be the output of the csv read and the other one to cancel the unmarshalling.

**Comment by timblackwell** [comment]
Is there any way to detect that the reader is close and nothing left to read?
If not then I would agree adding a cancelation channel would be to natural route forward.

Would you accept a pull request adding this functionality using this approach?

**Comment by pikanezi** [comment]
Yes of course :) I will look into why does closing the reader does not stop the reading, looks suspicious to me.

**Comment by timblackwell** [comment]
Closing the reader does produce an error and stop the marshalling process. My problem was with my surrounding code, forgetting to close the channel. Only if the marshalling completes successfully is the channel closed.
